### PR TITLE
add fake input element to solve form element issue

### PR DESCRIPTION
**Pull request by slavik-lvovsky**

### CODE REVIEW

**Comment by tomer-epstein** [comment]
please add link to the vue issue,

**Comment by slavik-lvovsky** [comment]
The form issue information:
https://forum.vuejs.org/t/modal-form-submit-always-reloads-page/1279
https://stackoverflow.com/questions/1370021/why-does-forms-with-single-input-field-submit-upon-pressing-enter-key-in-input

**Review by tomer-epstein — DISMISSED** [review]

**Comment by tomer-epstein** [comment]
Better doing this fix at - https://github.com/SAP/inquirer-gui/blob/master/src/Form.vue

**Comment by tomer-epstein** [comment]
https://github.com/SAP/inquirer-gui/pull/54

**Pull request closed without merging**
