### PR TITLE
Back feature

### PR DESCRIPTION
**Pull request by perspectivus1**

### CODE REVIEW

**Comment by tomer-epstein** [comment]
Tested with generator-foodq.
'Hunfer Info' step: are you hungry? Yes , beer? ['Paulner']
Click Next.
'Hunger Level' step: fill whatever
Click Back
'Hunfer Info' step: are you hungry? No
Click Next. Next .... till the End

Open public\index.html
actual: answers contains Food && beers values
expected answers values for Foo & beers should be undefined.

**Comment by tomer-epstein** [comment]
Tested with generator-foodq.
'Hunger Info' step: fill whatever
Click Next.
'Hunger Level' step: don't fill
Click Back
'Hunger Info' don't change
Click Next. 
'Hunger Level' step: 'ho hungry are you?' select 'very'

Actual: Did you enjoy your meal?' shows 'Click to display the list of options'
Expected: 'Did you enjoy your meal?' to have a value

**Comment by slavik-lvovsky** [comment]
1. Back button should not be displayed in generators prompt
2. It should be possible to go back from first generator prompt to the generators prompt
3. In foodq --> Delivery prompt --> select No in the first question --> Address prompt disappears, but if you press Back it appears again
4. I see flickering in prompts map

Very good job !!!

**Comment by tomer-epstein** [comment]
> Tested with generator-foodq.
> 'Hunger Info' step: fill whatever
> Click Next.
> 'Hunger Level' step: don't fill
> Click Back
> 'Hunger Info' don't change
> Click Next.
> 'Hunger Level' step: 'how hungry are you?' select 'very'
> 
> Actual: Did you enjoy your meal?' shows 'Click to display the list of options'
> Expected: 'Did you enjoy your meal?' to have a value

Fixed by https://github.com/SAP/yeoman-ui/pull/184/commits/963a11084cac95574e289d00d85f12b1c5a22e15

**Pull request merged**
