### PR TITLE
Add SWATracker object to options sent to generators.

### PR DESCRIPTION
**Pull request by ira-gordin-sap**

### CODE REVIEW

**Review by tomer-epstein — CHANGES_REQUESTED** [review]
looks good. 
please update generator-foodq to use the SWA.

**Comment by ira-gordin-sap** [comment]
> looks good.
> please update generator-foodq to use the SWA.

How? What it should do with it?

**Comment by tomer-epstein** [comment]
> > looks good.
> > please update generator-foodq to use the SWA.
> 
> How? What it should do with it?

report usage.

**Comment by ira-gordin-sap** [comment]
> > > looks good.
> > > please update generator-foodq to use the SWA.
> > 
> > 
> > How? What it should do with it?
> 
> report usage.

Report usage for what?
We don't have such requirement.

**Review by tomer-epstein — APPROVED** [review]

**Pull request merged**
